//! Extract direct dependencies at build time and emit a static Rust table so
//! the About panel can show a live, un-forgettable list.
//!
//! Only "normal" (runtime) direct dependencies of the root package are
//! included; build-deps and dev-deps are omitted. License and version come
//! from each crate's own Cargo.toml (`license` or `license-file`) via
//! `cargo metadata`, so there is no manual list to keep in sync.
//!
//! Per-crate purpose text ("why we use this crate") is NOT auto-generatable. It
//! is user-facing prose, so it lives in the language packs
//! (`web/lang/*.json`, key `about.crate.<name>`) and is edited by hand when a
//! dependency is added.

use std::fs;
use std::path::{Path, PathBuf};

use cargo_metadata::{DependencyKind, MetadataCommand};

fn main() {
    embed_windows_resource();
    emit_build_id();

    let meta = MetadataCommand::new()
        .exec()
        .expect("failed to run `cargo metadata`");

    let root = meta
        .root_package()
        .expect("no root package (workspace root?)");

    // Resolved direct *runtime* dependencies, identified by package id.
    //
    // Matching on ids rather than names matters: the graph can hold two versions
    // of one crate (a build-dependency pulled in `toml 1.x` while the binary
    // links `toml 0.8`), and a name filter listed both — crediting a build-only
    // crate as if it shipped inside the exe, twice over.
    let resolve = meta
        .resolve
        .as_ref()
        .expect("`cargo metadata` returned no resolve graph");
    let root_node = resolve
        .nodes
        .iter()
        .find(|n| n.id == root.id)
        .expect("root package missing from the resolve graph");
    let direct_ids: std::collections::HashSet<_> = root_node
        .deps
        .iter()
        // An empty `dep_kinds` means the cargo that produced this metadata did not
        // report kinds at all; treat that as a normal dependency rather than
        // silently emitting an empty list.
        .filter(|d| {
            d.dep_kinds.is_empty() || d.dep_kinds.iter().any(|k| k.kind == DependencyKind::Normal)
        })
        .map(|d| d.pkg.clone())
        .collect();

    let mut entries: Vec<(String, String, String)> = meta
        .packages
        .iter()
        .filter(|p| direct_ids.contains(&p.id))
        .map(|p| {
            let license = p.license.clone().unwrap_or_else(|| {
                p.license_file
                    .as_ref()
                    .map(|_| "custom".to_string())
                    .unwrap_or_else(|| "unknown".to_string())
            });
            (p.name.clone(), p.version.to_string(), license)
        })
        .collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// AUTO-GENERATED by build.rs from `cargo metadata`. Do not edit.\n\
         pub static OSS_LIST: &[(&str, &str, &str)] = &[\n",
    );
    for (name, version, license) in &entries {
        out.push_str(&format!(
            "    ({:?}, {:?}, {:?}),\n",
            name, version, license
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = PathBuf::from(&out_dir).join("oss_list.rs");
    fs::write(&path, out).expect("write oss_list.rs");

    // Rebuild the list only when the dep set changes.
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=Cargo.lock");
}

/// Stamp the binary with the git short hash it was built from (plus a
/// `-dirty` suffix when the working tree had uncommitted changes), so a
/// running instance's origin can be told apart from a rebuild without
/// relying on `Cargo.toml`'s version, which does not change every build.
/// Falls back to `"unknown"` when git is unavailable (e.g. a release
/// tarball built outside a git checkout).
fn emit_build_id() {
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short=8", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    let dirty = std::process::Command::new("git")
        .args(["status", "--porcelain"])
        .output()
        .ok()
        .is_some_and(|o| o.status.success() && !o.stdout.is_empty());

    let build_id = if dirty { format!("{hash}-dirty") } else { hash };
    println!("cargo:rustc-env=AUDIOREMOTE_BUILD_ID={build_id}");
    // The git hash/dirty state can't be tracked by file mtime, so always
    // let cargo decide whether a rebuild is otherwise needed.
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/index");
}

/// Embed the app icon + metadata into the .exe as a Windows resource so the
/// binary shows the correct icon in Explorer, taskbar, Alt-Tab, and its
/// Properties dialog. No-ops on non-Windows targets and when the `.ico` is
/// missing (e.g. before `make-icon` has been run), so cross-compiles and
/// first-time clones still build.
fn embed_windows_resource() {
    let is_windows = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    if !is_windows {
        return;
    }

    let icon_path = "web/icons/favicon.ico";
    println!("cargo:rerun-if-changed={icon_path}");
    if !Path::new(icon_path).exists() {
        println!(
            "cargo:warning=icon {icon_path} not found; the .exe will have no embedded icon. \
             Run make-icon to regenerate."
        );
        return;
    }

    let mut res = winresource::WindowsResource::new();
    res.set_icon(icon_path);

    // The manifest is a hard requirement, not a nicety: it declares the
    // comctl32 v6 dependency that `TaskDialogIndirect` needs to resolve. An exe
    // built without it does not fail at runtime — it fails to *load*, with a
    // Windows error dialog and no clue why. So this panics rather than warns.
    let manifest_path = "packaging/audioremote.manifest";
    println!("cargo:rerun-if-changed={manifest_path}");
    assert!(
        Path::new(manifest_path).exists(),
        "{manifest_path} is missing. It is listed in Cargo.toml's `include`, so a crates.io \
         tarball carries it too; if it really is gone, restore it before building — the exe \
         will not start without it."
    );
    res.set_manifest_file(manifest_path);
    res.set(
        "FileDescription",
        "audioremote — Windows 11 audio output remote",
    );
    res.set("ProductName", "audioremote");
    res.set(
        "LegalCopyright",
        "Copyright (c) 2026 Hiroshi Ishizaka (ishizakahiroshi)",
    );
    if let Err(e) = res.compile() {
        println!("cargo:warning=failed to embed Windows resource: {e}");
    }
}
