//! "About this app" response. Bundles product identity + generated OSS list
//! + hand-curated per-crate purpose text.

use serde::Serialize;

// Generated by build.rs: `pub static OSS_LIST: &[(&str, &str, &str)]` — tuples
// of (name, version, license).
include!(concat!(env!("OUT_DIR"), "/oss_list.rs"));

#[derive(Serialize)]
pub struct AboutResponse {
    pub app: AppInfo,
    pub oss: Vec<OssEntry>,
}

#[derive(Serialize)]
pub struct AppInfo {
    pub name: &'static str,
    pub version: &'static str,
    pub license: &'static str,
    pub copyright: &'static str,
    pub description: &'static str,
    /// Note about the frontend (0 third-party deps).
    pub frontend_note: &'static str,
}

#[derive(Serialize)]
pub struct OssEntry {
    pub name: &'static str,
    pub version: &'static str,
    pub license: &'static str,
    pub purpose: &'static str,
}

pub fn build() -> AboutResponse {
    AboutResponse {
        app: AppInfo {
            name: env!("CARGO_PKG_NAME"),
            version: env!("CARGO_PKG_VERSION"),
            license: "MIT",
            copyright: "2026 Hiroshi Ishizaka (ishizakahiroshi)",
            description: env!("CARGO_PKG_DESCRIPTION"),
            frontend_note: "フロントエンド（HTML / CSS / JS）は外部ライブラリを一切使わず、手書きの vanilla JavaScript で実装しています。npm / bundler / フレームワーク非依存。",
        },
        oss: OSS_LIST
            .iter()
            .map(|(name, version, license)| OssEntry {
                name,
                version,
                license,
                purpose: purpose_for(name),
            })
            .collect(),
    }
}

/// Hand-curated "why we use this" text. Keep in sync when adding a new direct
/// dependency; unknown entries fall through to an empty string.
fn purpose_for(name: &str) -> &'static str {
    match name {
        "axum" => "HTTP サーバーフレームワーク",
        "tokio" => "非同期ランタイム",
        "serde" => "シリアライズ基盤",
        "serde_json" => "JSON 生成 / パース",
        "toml" => "config.toml / history.toml 読み書き",
        "getrandom" => "OS 乱数によるトークン採番",
        "rust-embed" => "Web UI 資産の exe 埋め込み",
        "local-ip-address" => "LAN NIC の自動列挙",
        "windows" => "Windows Core Audio / 非公開 IPolicyConfig COM バインディング (Microsoft)",
        "windows-core" => "windows crate の共通コア (Microsoft)",
        _ => "",
    }
}
