//! "About this app" response. Bundles product identity + generated OSS list
//! + hand-curated per-crate purpose text.

use serde::Serialize;

// Generated by build.rs: `pub static OSS_LIST: &[(&str, &str, &str)]` — tuples
// of (name, version, license).
include!(concat!(env!("OUT_DIR"), "/oss_list.rs"));

#[derive(Serialize)]
pub struct AboutResponse {
    pub app: AppInfo,
    pub oss: Vec<OssEntry>,
}

#[derive(Serialize)]
pub struct AppInfo {
    pub name: &'static str,
    pub version: &'static str,
    pub build_id: &'static str,
    pub license: &'static str,
    pub copyright: &'static str,
    /// Cargo's package description — English, because crates.io shows it. The Web
    /// UI prefers its own localized `about.description` and falls back to this.
    pub description: &'static str,
    pub repository: &'static str,
    pub author_site: &'static str,
    /// Base URL the Web UI appends a pre-filled `?body=` to.
    pub issues_new: &'static str,
    /// Host OS summary for bug reports, e.g. `Windows 11 24H2 (build 26100,
    /// x86_64)`. Only ever leaves the host through the authenticated
    /// `/api/about` route.
    pub os: String,
}

/// One bundled crate. Deliberately facts only — the "why we use it" note is
/// user-facing prose and lives in the language packs (`web/lang/*.json`, key
/// `about.crate.<name>`) so it follows the UI language like everything else.
#[derive(Serialize)]
pub struct OssEntry {
    pub name: &'static str,
    pub version: &'static str,
    pub license: &'static str,
}

/// Personal site of the author. Not derivable from Cargo metadata (`homepage`
/// points at the repository), so it is spelled out here.
const AUTHOR_SITE: &str = "https://ishizakahiroshi.com/";

pub fn build() -> AboutResponse {
    AboutResponse {
        app: AppInfo {
            name: env!("CARGO_PKG_NAME"),
            version: env!("CARGO_PKG_VERSION"),
            build_id: env!("AUDIOREMOTE_BUILD_ID"),
            license: "MIT",
            copyright: "2026 Hiroshi Ishizaka (ishizakahiroshi)",
            description: env!("CARGO_PKG_DESCRIPTION"),
            repository: env!("CARGO_PKG_REPOSITORY"),
            author_site: AUTHOR_SITE,
            issues_new: concat!(env!("CARGO_PKG_REPOSITORY"), "/issues/new"),
            os: os_description(),
        },
        oss: OSS_LIST
            .iter()
            .map(|(name, version, license)| OssEntry {
                name,
                version,
                license,
            })
            .collect(),
    }
}

/// Human-readable host OS summary, e.g. `Windows 11 24H2 (build 26100,
/// x86_64)`. Used by the Web UI's bug-report link.
///
/// `ProductName` is deliberately not read: it still says "Windows 10 Pro" on
/// Windows 11, so the family is derived from the build number instead.
#[cfg(windows)]
fn os_description() -> String {
    let build = registry_current_version("CurrentBuild");
    let display = registry_current_version("DisplayVersion");

    // 22000 is the first Windows 11 build. Older builds keep the neutral
    // label — the number itself is what a bug report actually needs.
    let family = match build.as_deref().and_then(|b| b.parse::<u32>().ok()) {
        Some(n) if n >= 22000 => "Windows 11",
        _ => "Windows",
    };

    let arch = std::env::consts::ARCH;
    match (display, build) {
        (Some(display), Some(build)) => format!("{family} {display} (build {build}, {arch})"),
        (None, Some(build)) => format!("{family} (build {build}, {arch})"),
        (Some(display), None) => format!("{family} {display} ({arch})"),
        (None, None) => format!("{family} ({arch})"),
    }
}

#[cfg(not(windows))]
fn os_description() -> String {
    format!("{} ({})", std::env::consts::OS, std::env::consts::ARCH)
}

/// Read one REG_SZ value from `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion`.
/// Returns `None` for any failure — a missing OS string only degrades the
/// pre-filled report, so it must never fail the About response.
#[cfg(windows)]
fn registry_current_version(value_name: &str) -> Option<String> {
    use windows::core::{w, PCWSTR};
    use windows::Win32::Foundation::ERROR_SUCCESS;
    use windows::Win32::System::Registry::{RegGetValueW, HKEY_LOCAL_MACHINE, RRF_RT_REG_SZ};

    let name: Vec<u16> = value_name
        .encode_utf16()
        .chain(std::iter::once(0))
        .collect();
    let mut buf = [0u16; 128];
    let mut size = std::mem::size_of_val(&buf) as u32;

    let status = unsafe {
        RegGetValueW(
            HKEY_LOCAL_MACHINE,
            w!("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion"),
            PCWSTR(name.as_ptr()),
            RRF_RT_REG_SZ,
            None,
            Some(buf.as_mut_ptr().cast()),
            Some(&mut size),
        )
    };
    if status != ERROR_SUCCESS {
        return None;
    }

    // `size` comes back as the byte count written, including the trailing NUL.
    let chars = (size as usize / 2).saturating_sub(1).min(buf.len());
    let value = String::from_utf16_lossy(&buf[..chars]).trim().to_string();
    (!value.is_empty()).then_some(value)
}

// The per-crate "why we use this" text used to live here as hardcoded Japanese,
// which meant the English UI showed Japanese notes. It now lives in every
// language pack under `about.crate.<name>`; add a key there when adding a direct
// dependency (a missing key simply renders no note).

#[cfg(test)]
mod tests {
    use super::OSS_LIST;

    /// Guards the About panel against the defect that put Japanese text in the
    /// English UI: every bundled crate needs a purpose note in **every** language
    /// pack, and the moment a dependency is added without one, this fails.
    #[test]
    fn every_language_pack_covers_the_bundled_crates() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("web/lang");
        let mut packs = 0;

        for entry in std::fs::read_dir(&dir).expect("web/lang is readable") {
            let path = entry.expect("directory entry").path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            let text = std::fs::read_to_string(&path).expect("read language pack");
            let pack: serde_json::Value = serde_json::from_str(&text)
                .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()));
            packs += 1;

            let has = |key: &str| {
                pack.get(key)
                    .and_then(|v| v.as_str())
                    .is_some_and(|s| !s.trim().is_empty())
            };

            // Prose that used to come from the server as hardcoded Japanese.
            for key in ["about.description", "about.frontendBody"] {
                assert!(has(key), "{} is missing {key}", path.display());
            }
            for (name, _version, _license) in OSS_LIST {
                let key = format!("about.crate.{name}");
                assert!(has(&key), "{} is missing {key}", path.display());
            }
        }

        assert!(
            packs >= 2,
            "expected at least the ja and en packs, found {packs}"
        );
    }
}
